create table person(
  person_id int generated by default as identity primary key,
  name varchar(100) not null unique,
  yearOfBirth int not null
);
create table book(
    id_book int generated by default as identity primary key,
    person_id int references person(person_id) on delete set null,
    name_book varchar(100) not null,
    year_book int not null,
    author_book varchar(100) not null,
    time_at timestamp
);
select * from person;
select * from book;




